module.exports.CricketBallIcon=require('./CricketBallIcon.js');'
module.exports.FootballAIcon=require('./FootballAIcon.js');'
module.exports.FootballIcon=require('./FootballIcon.js');'
module.exports.HockeyIcon=require('./HockeyIcon.js');'
module.exports.RugbyHelbetIcon=require('./RugbyHelbetIcon.js');'
module.exports.TennisIcon=require('./TennisIcon.js');'
module.exports.YogaMatIcon=require('./YogaMatIcon.js');'
